version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - dbapp:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}  
      - POSTGRES_DB=${DB_NAME}
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ganeshcom-course
    restart: on-failure
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db          
    volumes:
      - ./src:/app/src
  
volumes:
  dbapp: